services:
  - type: web
    name: src-gorodishche
    runtime: python
    buildCommand: ./build.sh
    preDeployCommand: ./predeploy.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
