# Generated by Django 4.2.30 on 2026-05-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone_primary', models.CharField(max_length=50, verbose_name='Телефон 1 (отображение)')),
                ('phone_primary_tel', models.CharField(blank=True, max_length=30, verbose_name='Телефон 1 (для ссылки tel:)')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2 (отображение)')),
                ('phone_secondary_tel', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2 (для ссылки tel:)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('work_weekdays', models.CharField(default='8:30 — 17:30', max_length=100, verbose_name='Режим Пн–Пт')),
                ('work_break', models.CharField(default='12:00 — 13:00', max_length=100, verbose_name='Перерыв')),
                ('work_weekend', models.CharField(default='Выходной', max_length=100, verbose_name='Сб — Вс')),
                ('map_placeholder', models.CharField(blank=True, max_length=300, verbose_name='Текст на блоке карты')),
                ('reception_director', models.TextField(blank=True, verbose_name='Личный приём директора')),
                ('reception_written', models.TextField(blank=True, verbose_name='Письменные обращения')),
                ('reception_online', models.TextField(blank=True, verbose_name='Онлайн-обращения')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('kontakty', 'Контакты'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты')], max_length=50, verbose_name='Страница')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст (абзацы через пустую строку)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Текстовый блок',
                'verbose_name_plural': 'Текстовые блоки',
                'ordering': ['page_slug', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('label', models.CharField(max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Показатель на главной',
                'verbose_name_plural': 'Показатели на главной',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('index_main', 'Главная — 3 карточки'), ('index_bottom', 'Главная — 2 карточки'), ('social_top', 'Соц. услуги — 3 карточки'), ('dnevnoe_top', 'Дневное — 3 карточки'), ('appeal_cards', 'Обращения — 2 карточки')], max_length=30, verbose_name='Размещение')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка (эмодзи)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_url_name', models.CharField(blank=True, choices=[('', '— без ссылки —'), ('index', 'Главная'), ('socialnye_uslugi', 'Социальные услуги'), ('perechen_uslug', 'Перечень услуг'), ('dnevnoe_otdelenie', 'Дневное отделение'), ('rabota_s_obrascheniyami', 'Работа с обращениями'), ('kontakty', 'Контакты'), ('novosti', 'Новости'), ('pravovye_akty', 'Правовые акты')], max_length=50, verbose_name='Ссылка')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Текст ссылки')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Информационная карточка',
                'verbose_name_plural': 'Информационные карточки',
                'ordering': ['placement', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок раздела')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел правовых актов',
                'verbose_name_plural': 'Разделы правовых актов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('kontakty', 'Контакты'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты')], unique=True, verbose_name='Код страницы')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Заголовок вкладки браузера')),
                ('badge', models.CharField(blank=True, max_length=200, verbose_name='Бейдж')),
                ('h1', models.CharField(max_length=300, verbose_name='Заголовок H1')),
                ('intro', models.TextField(blank=True, verbose_name='Вводный текст / описание')),
                ('hero_button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки в шапке-блоке')),
                ('hero_button_url', models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки (имя url или http)')),
                ('free_banner_text', models.CharField(blank=True, max_length=300, verbose_name='Баннер «бесплатно»')),
                ('block_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок доп. блока')),
                ('block_content', models.TextField(blank=True, verbose_name='Содержимое доп. блока')),
                ('dark_card_title', models.CharField(blank=True, max_length=200, verbose_name='Тёмная карточка — заголовок')),
                ('dark_card_text', models.TextField(blank=True, verbose_name='Тёмная карточка — текст')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Категория услуг')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Городищенский СРЦ', max_length=200, verbose_name='Название в шапке')),
                ('footer_text', models.CharField(default='© 2026 ГКСУ СО «Городищенский социально-реабилитационный центр для несовершеннолетних»', max_length=500, verbose_name='Текст в подвале')),
                ('gosuslugi_url', models.URLField(default='https://www.gosuslugi.ru/', verbose_name='Ссылка на Госуслуги')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Услуга')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Пункт')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.contentsection', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Пункт списка',
                'verbose_name_plural': 'Пункты списка',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Акт')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.legalsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Правовой акт',
                'verbose_name_plural': 'Правовые акты',
                'ordering': ['order'],
            },
        ),
    ]
