# Generated by Django 4.2.30 on 2026-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Вставьте HTML с Яндекс.Карт (Поделиться → Вставить карту). Если заполнено — координаты не используются.', verbose_name='Код карты (iframe)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Например: 48.706200', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Например: 44.481500', max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=16, verbose_name='Масштаб карты'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='show_map',
            field=models.BooleanField(default=True, verbose_name='Показывать карту'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_placeholder',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст-заглушка (если карта выключена)'),
        ),
    ]
