# Generated by Django 4.2.30 on 2026-06-08 11:11

from django.db import migrations, models
from django.utils.text import slugify


def fill_news_slugs(apps, schema_editor):
    News = apps.get_model('main', 'News')
    for news in News.objects.all():
        if news.slug:
            continue
        base = slugify(news.title, allow_unicode=True) or f'news-{news.pk}'
        slug = base
        n = 1
        while News.objects.filter(slug=slug).exclude(pk=news.pk).exists():
            n += 1
            slug = f'{base}-{n}'
        news.slug = slug
        news.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactinfo_map_iframe_contactinfo_map_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, verbose_name='Полный текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, null=True, verbose_name='Адрес страницы'),
        ),
        migrations.RunPython(fill_news_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='Адрес страницы'),
        ),
    ]
