# Generated by Django 4.2.30 on 2026-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_slug_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('contacts', 'Контакты — документы'), ('rules', 'Внутренние локальные акты'), ('pravila', 'Правила внутреннего распорядка'), ('popech', 'Попечительский совет')], max_length=20, verbose_name='Раздел')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='about/docs/', verbose_name='Файл')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Документ об учреждении',
                'verbose_name_plural': 'Документы об учреждении',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=200, verbose_name='Сокращённое наименование')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=20, verbose_name='КПП')),
                ('okpo', models.CharField(max_length=20, verbose_name='ОКПО')),
                ('ogrn', models.CharField(max_length=20, verbose_name='ОГРН')),
                ('registration_info', models.TextField(blank=True, verbose_name='Дата регистрации')),
                ('founder_info', models.TextField(blank=True, verbose_name='Учредитель')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='Директор')),
                ('property_type', models.CharField(blank=True, max_length=300, verbose_name='Вид собственности')),
                ('branch_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес структурного подразделения')),
                ('branch_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон подразделения')),
                ('main_building_photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото здания (Городище)')),
                ('branch_building_photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото здания (Иловля)')),
            ],
            options={
                'verbose_name': 'Сведения об учреждении',
                'verbose_name_plural': 'Сведения об учреждении',
            },
        ),
        migrations.CreateModel(
            name='RegionalSocialCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='№')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Центр соцзащиты области',
                'verbose_name_plural': 'Центры соцзащиты области',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сотрудник руководства',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='page_slug',
            field=models.CharField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('ob-uchrezhdenii', 'Об учреждении'), ('ob-uchrezhdenii-kontakty', 'Об учреждении — контакты'), ('ob-uchrezhdenii-polnomochiya', 'Об учреждении — полномочия'), ('ob-uchrezhdenii-rukovodstvo', 'Об учреждении — руководство'), ('ob-uchrezhdenii-lokalnye-akty', 'Об учреждении — локальные акты'), ('ob-uchrezhdenii-pravila', 'Об учреждении — правила распорядка'), ('ob-uchrezhdenii-popechitelskiy-sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты')], max_length=50, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='link_url_name',
            field=models.CharField(blank=True, choices=[('', '— без ссылки —'), ('index', 'Главная'), ('socialnye_uslugi', 'Социальные услуги'), ('perechen_uslug', 'Перечень услуг'), ('dnevnoe_otdelenie', 'Дневное отделение'), ('rabota_s_obrascheniyami', 'Работа с обращениями'), ('ob_uchrezhdenii', 'Об учреждении'), ('ob_uchrezhdenii_kontakty', 'Об учреждении — контакты'), ('ob_uchrezhdenii_polnomochiya', 'Об учреждении — полномочия'), ('ob_uchrezhdenii_rukovodstvo', 'Об учреждении — руководство'), ('ob_uchrezhdenii_lokalnye_akty', 'Об учреждении — локальные акты'), ('ob_uchrezhdenii_pravila', 'Об учреждении — правила распорядка'), ('ob_uchrezhdenii_popechitelskiy_sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye_akty', 'Правовые акты')], max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('ob-uchrezhdenii', 'Об учреждении'), ('ob-uchrezhdenii-kontakty', 'Об учреждении — контакты'), ('ob-uchrezhdenii-polnomochiya', 'Об учреждении — полномочия'), ('ob-uchrezhdenii-rukovodstvo', 'Об учреждении — руководство'), ('ob-uchrezhdenii-lokalnye-akty', 'Об учреждении — локальные акты'), ('ob-uchrezhdenii-pravila', 'Об учреждении — правила распорядка'), ('ob-uchrezhdenii-popechitelskiy-sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты')], unique=True, verbose_name='Код страницы'),
        ),
    ]
