# Generated by Django 4.2.30 on 2026-06-08 13:19

from django.db import migrations, models


def clear_legal_sections(apps, schema_editor):
    apps.get_model('main', 'LegalSection').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutdocument_institutionprofile_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_legal_sections, migrations.RunPython.noop),
        migrations.AddField(
            model_name='legalitem',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='legalitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='legal/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='legalsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Код раздела'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='page_slug',
            field=models.CharField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('ob-uchrezhdenii', 'Об учреждении'), ('ob-uchrezhdenii-kontakty', 'Об учреждении — контакты'), ('ob-uchrezhdenii-polnomochiya', 'Об учреждении — полномочия'), ('ob-uchrezhdenii-rukovodstvo', 'Об учреждении — руководство'), ('ob-uchrezhdenii-lokalnye-akty', 'Об учреждении — локальные акты'), ('ob-uchrezhdenii-pravila', 'Об учреждении — правила распорядка'), ('ob-uchrezhdenii-popechitelskiy-sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты'), ('pravovye-akty-akty', 'Правовые акты — НПА'), ('pravovye-akty-ustav', 'Правовые акты — устав'), ('pravovye-akty-litsenzii', 'Правовые акты — лицензии'), ('pravovye-akty-federal', 'Правовые акты — федеральное'), ('pravovye-akty-regional', 'Правовые акты — региональное'), ('pravovye-akty-normativy', 'Правовые акты — нормативы'), ('pravovye-akty-sout', 'Правовые акты — СОУТ')], max_length=50, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('ob-uchrezhdenii', 'Об учреждении'), ('ob-uchrezhdenii-kontakty', 'Об учреждении — контакты'), ('ob-uchrezhdenii-polnomochiya', 'Об учреждении — полномочия'), ('ob-uchrezhdenii-rukovodstvo', 'Об учреждении — руководство'), ('ob-uchrezhdenii-lokalnye-akty', 'Об учреждении — локальные акты'), ('ob-uchrezhdenii-pravila', 'Об учреждении — правила распорядка'), ('ob-uchrezhdenii-popechitelskiy-sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты'), ('pravovye-akty-akty', 'Правовые акты — НПА'), ('pravovye-akty-ustav', 'Правовые акты — устав'), ('pravovye-akty-litsenzii', 'Правовые акты — лицензии'), ('pravovye-akty-federal', 'Правовые акты — федеральное'), ('pravovye-akty-regional', 'Правовые акты — региональное'), ('pravovye-akty-normativy', 'Правовые акты — нормативы'), ('pravovye-akty-sout', 'Правовые акты — СОУТ')], unique=True, verbose_name='Код страницы'),
        ),
    ]
