# Generated by Django 4.2.30 on 2026-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_currentactivitysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NokContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_html', models.TextField(blank=True, verbose_name='Содержимое (HTML)')),
            ],
            options={
                'verbose_name': 'Независимая оценка качества НОК',
                'verbose_name_plural': 'Независимая оценка качества НОК',
            },
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='page_slug',
            field=models.CharField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('ob-uchrezhdenii', 'Об учреждении'), ('ob-uchrezhdenii-kontakty', 'Об учреждении — контакты'), ('ob-uchrezhdenii-polnomochiya', 'Об учреждении — полномочия'), ('ob-uchrezhdenii-rukovodstvo', 'Об учреждении — руководство'), ('ob-uchrezhdenii-lokalnye-akty', 'Об учреждении — локальные акты'), ('ob-uchrezhdenii-pravila', 'Об учреждении — правила распорядка'), ('ob-uchrezhdenii-popechitelskiy-sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты'), ('pravovye-akty-akty', 'Правовые акты — НПА'), ('pravovye-akty-ustav', 'Правовые акты — устав'), ('pravovye-akty-litsenzii', 'Правовые акты — лицензии'), ('pravovye-akty-federal', 'Правовые акты — федеральное'), ('pravovye-akty-regional', 'Правовые акты — региональное'), ('pravovye-akty-normativy', 'Правовые акты — нормативы'), ('pravovye-akty-sout', 'Правовые акты — СОУТ'), ('tekushchaya-deyatelnost', 'Текущая деятельность'), ('nezavisimaya-otsenka-nok', 'Независимая оценка качества НОК')], max_length=50, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='link_url_name',
            field=models.CharField(blank=True, choices=[('', '— без ссылки —'), ('index', 'Главная'), ('socialnye_uslugi', 'Социальные услуги'), ('perechen_uslug', 'Перечень услуг'), ('dnevnoe_otdelenie', 'Дневное отделение'), ('rabota_s_obrascheniyami', 'Работа с обращениями'), ('ob_uchrezhdenii', 'Об учреждении'), ('ob_uchrezhdenii_kontakty', 'Об учреждении — контакты'), ('ob_uchrezhdenii_polnomochiya', 'Об учреждении — полномочия'), ('ob_uchrezhdenii_rukovodstvo', 'Об учреждении — руководство'), ('ob_uchrezhdenii_lokalnye_akty', 'Об учреждении — локальные акты'), ('ob_uchrezhdenii_pravila', 'Об учреждении — правила распорядка'), ('ob_uchrezhdenii_popechitelskiy_sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye_akty', 'Правовые акты'), ('tekushchaya_deyatelnost', 'Текущая деятельность'), ('nezavisimaya_otsenka_nok', 'Независимая оценка качества НОК')], max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(choices=[('index', 'Главная'), ('socialnye-uslugi', 'Социальные услуги'), ('perechen-uslug', 'Перечень услуг'), ('dnevnoe-otdelenie', 'Дневное отделение'), ('rabota-s-obrascheniyami', 'Работа с обращениями'), ('ob-uchrezhdenii', 'Об учреждении'), ('ob-uchrezhdenii-kontakty', 'Об учреждении — контакты'), ('ob-uchrezhdenii-polnomochiya', 'Об учреждении — полномочия'), ('ob-uchrezhdenii-rukovodstvo', 'Об учреждении — руководство'), ('ob-uchrezhdenii-lokalnye-akty', 'Об учреждении — локальные акты'), ('ob-uchrezhdenii-pravila', 'Об учреждении — правила распорядка'), ('ob-uchrezhdenii-popechitelskiy-sovet', 'Об учреждении — попечительский совет'), ('novosti', 'Новости'), ('pravovye-akty', 'Правовые акты'), ('pravovye-akty-akty', 'Правовые акты — НПА'), ('pravovye-akty-ustav', 'Правовые акты — устав'), ('pravovye-akty-litsenzii', 'Правовые акты — лицензии'), ('pravovye-akty-federal', 'Правовые акты — федеральное'), ('pravovye-akty-regional', 'Правовые акты — региональное'), ('pravovye-akty-normativy', 'Правовые акты — нормативы'), ('pravovye-akty-sout', 'Правовые акты — СОУТ'), ('tekushchaya-deyatelnost', 'Текущая деятельность'), ('nezavisimaya-otsenka-nok', 'Независимая оценка качества НОК')], unique=True, verbose_name='Код страницы'),
        ),
    ]
